//Accepted
#include<stdio.h>
#include<string.h>
#include<math.h>
int main()
{
    char d[150][150],ch,c[150][150],h;
    int i,j,n,m,a,b,e,k=1,y=0;
    while(1)
    {
    for(i=0;i<150;i++)
    {
        for(j=0;j<150;j++)
        {
          d[i][j]='0';
        }
    }
    scanf("%d%d",&n,&m);
    if(n==0&&m==0)
    break;
     if(y>0)
    printf("\n");
    h=getchar();
    for(i=1;i<=n;i++)
    {
        for(j=1;j<=m;j++)
        {
            scanf("%c",&ch);
            if(ch=='.')
            d[i][j]='0';
            else
            d[i][j]='1';
        }
        h=getchar();
    }
    for(i=1;i<=n;i++)
    {
        for(j=1;j<=m;j++)
        {
            if(d[i][j]=='1')
            c[i][j]='*';
            else
            {
            a=(d[i-1][j-1]-48)+(d[i-1][j]-48)+(d[i-1][j+1]-48);
            b=(d[i][j-1]-48)+(d[i][j+1]-48);
            e=(d[i+1][j-1]-48)+(d[i+1][j]-48)+(d[i+1][j+1]-48);
            c[i][j]=a+b+e+48;
            }
        }
    }
   printf("Field #%d:\n",k);
    for(i=1;i<=n;i++)
    {
        for(j=1;j<=m;j++)
        {
           printf("%c",c[i][j]);
        }
        printf("\n");
    }
    k++;
    y=1;
    }
    return 0;
}
