#include<stdio.h>
#include<string.h>
#include<math.h>
#include<stdlib.h>
int main()
{
    long long int i,p,list[100],j;
    long long N,c,k,v,tem;
    while(scanf("%lld",&N))
    {
        if(N==0)
        break;
        v=N;
        if(N<0)
        N=-1*N;
        i=2;
        j=0;
        p=1;
        k=1;
        while(i<=(long long)sqrt(N))
        {
            j=0;
            while(N%i==0)
            {
                j++;
                N=N/i;
            }
            if(j>0)
            list[k++]=j;
            i++;
        }
        if(N>1)
        list[k++]=1;
        if(k==2)
        {
            if(v<0&&list[k-1]%2==0)
            {
                tem=list[k-1]/2;
                if(tem%2==0)
                printf("1\n");
                else
                printf("%lld\n",tem);
            }
            else
            printf("%lld\n",list[k-1]);
        }
        else
        {
            int count=0;
            for(i=1;i<=k-2;i++)
            {
                if(list[i]==list[i+1])
                {
                    count++;
                }
            }
            if(count==k-2)
            {
                if(v<0&&list[1]%2==0)
                {
                tem=list[1]/2;
                if(tem%2==0)
                printf("1\n");
                else
                printf("%lld\n",tem);
                }
                else
                printf("%lld\n",list[1]);
            }
            else
            printf("1\n");
        }
    }
    return 0;
}
