//Accepted
#include<stdio.h>
int main()
{
    int H1,M1,H2,M2,a,b;
    while(1)
    {
        scanf("%d%d%d%d",&H1,&M1,&H2,&M2);
        if(H1==0&&H2==0&&M1==0&&M2==0)
        break;
      if(M1<=M2&&H1<=H2)
      {
         a=(H2-H1)*60;
         b=(M2-M1)+a;
      }
      else
      if(M1>M2&&H1>=H2)
      {
          a=((H2+23)-H1)*60;
          b=(M2+60)-M1+a;
      }
      else
      if(M1<M2&&H1>H2)
      {
          a=(H2+24-H1)*60;
          b=M2-M1+a;
      }
      else
      if(M1>M2&&H1<=H2)
      {
          a=(H2-(H1+1))*60;
          b=(M2+60)-M1+a;
      }
      else
      if(M1<M2&&H1==H2)
      {
          b=M2-M1;
      }
      printf("%d\n",b);
    }
    return 0;
}
